name: Build and push docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: slawiko
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the clean tag
        env:
          GITHUB_REF: ${{ github.ref }}
        id: get-tag
        run: echo "tag=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            VERSION_ARG=${{ steps.get-tag.outputs.tag }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get-tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
